#!/bin/sh
#
# @name AirSide Iris Quadrotor SITL
#
# @type Quadrotor Wide
#

. ${R}etc/init.d-posix/airframes/10016_none_iris

param set-default SYS_HAS_MAG 1
param set-default EKF2_MAG_TYPE 1
param set-default EKF2_MAG_NOISE 0.1
param set-default UXRCE_DDS_SYNCT 0
param set-default COM_RC_IN_MODE 4
param set-default NAV_DLL_ACT 0
param set-default COM_OBL_RC_ACT 0
param set-default MPC_THR_HOVER 0.55
param set SIM_BAT_ENABLE 0
param set BAT1_SOURCE 1
param set BAT_LOW_THR 0.15
param set BAT_CRIT_THR 0.07
param set BAT_EMERGEN_THR 0.05
param set COM_LOW_BAT_ACT 3
param set COM_FLTT_LOW_ACT 0
