#!/bin/sh
#
# @name Gazebo vertex_lidar
#
# @type Quadrotor
#

PX4_GZ_WORLD=${PX4_GZ_WORLD:=wind_turbine}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=vertex_lidar}

param set-default COM_DISARM_PRFLT 0

. ${R}etc/init.d-posix/airframes/4001_gz_x500
